name: get advisories

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: install cargo deny
      run: cargo install --locked cargo-deny
    - name: check advisories
      run: cargo deny check advisories
